[[client]]
id = 1
connected_drone_ids = [3, 4]

[[drone]]
id = 3
connected_node_ids = [1, 11, 14, 2]
pdr = 0.04

[[drone]]
id = 4
connected_node_ids = [1, 10, 15, 5]
pdr = 0.05

[[drone]]
id = 10
connected_node_ids = [4, 18, 8, 12]
pdr = 0.03

[[drone]]
id = 11
connected_node_ids = [3, 9, 17, 13]
pdr = 0.06

[[client]]
id = 9
connected_drone_ids = [11, 7]

[[drone]]
id = 6
connected_node_ids = [7, 17, 2, 8]
pdr = 0.03

[[drone]]
id = 7
connected_node_ids = [9, 6, 18, 5]
pdr = 0.05

[[drone]]
id = 18
connected_node_ids = [10, 7, 19, 20]
pdr = 0.04

[[drone]]
id = 15
connected_node_ids = [4, 14, 19, 13]
pdr = 0.05

[[drone]]
id = 14
connected_node_ids = [3, 15, 16, 12]
pdr = 0.06

[[drone]]
id = 17
connected_node_ids = [11, 6, 16, 20]
pdr = 0.04

[[server]]
id = 2
connected_drone_ids = [3, 6]

[[server]]
id = 5
connected_drone_ids = [4, 7]

[[client]]
id = 19
connected_drone_ids = [18, 15]

[[server]]
id = 12
connected_drone_ids = [10, 14]

[[server]]
id = 20
connected_drone_ids = [18, 17]

[[client]]
id = 8
connected_drone_ids = [10, 6]

[[client]]
id = 16
connected_drone_ids = [14, 17]
