[[client]]
id = 1
connected_drone_ids = [4, 2]

[[drone]]
id = 4
connected_node_ids = [1, 2, 7, 8]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 3, 5]
pdr = 0.04

[[drone]]
id = 7
connected_node_ids = [4, 6, 11, 12]
pdr = 0.06

[[drone]]
id = 9
connected_node_ids = [5, 10, 14, 13]
pdr = 0.05

[[client]]
id = 3
connected_drone_ids = [2, 5]

[[drone]]
id = 5
connected_node_ids = [2, 9, 3, 8]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [4, 5, 12, 13]
pdr = 0.05

[[server]]
id = 28
connected_drone_ids = [22, 23]

[[server]]
id = 31
connected_drone_ids = [25, 26]

[[client]]
id = 15
connected_drone_ids = [16, 22]

[[server]]
id = 32
connected_drone_ids = [27, 26]

[[client]]
id = 10
connected_drone_ids = [9, 14]

[[client]]
id = 6
connected_drone_ids = [7, 11]

[[server]]
id = 18
connected_drone_ids = [24, 25, 12, 13]

[[server]]
id = 29
connected_drone_ids = [24, 23]

[[drone]]
id = 16
connected_node_ids = [15, 11, 22, 23]
pdr = 0.04

[[drone]]
id = 11
connected_node_ids = [7, 6, 16, 17]
pdr = 0.05

[[drone]]
id = 22
connected_node_ids = [28, 15, 16]
pdr = 0.04

[[drone]]
id = 24
connected_node_ids = [18, 29, 17, 30]
pdr = 0.06

[[drone]]
id = 17
connected_node_ids = [11, 24, 23, 12]
pdr = 0.05

[[drone]]
id = 23
connected_node_ids = [28, 29, 16, 17]
pdr = 0.04

[[drone]]
id = 19
connected_node_ids = [14, 25, 26, 13]
pdr = 0.06

[[drone]]
id = 14
connected_node_ids = [9, 10, 19, 20]
pdr = 0.05

[[drone]]
id = 25
connected_node_ids = [31, 18, 19, 30]
pdr = 0.05

[[drone]]
id = 27
connected_node_ids = [32, 20, 21]
pdr = 0.04

[[drone]]
id = 20
connected_node_ids = [14, 27, 26, 21]
pdr = 0.05

[[drone]]
id = 26
connected_node_ids = [31, 32, 19, 20]
pdr = 0.04

[[drone]]
id = 12
connected_node_ids = [7, 8, 18, 17]
pdr = 0.06

[[drone]]
id = 13
connected_node_ids = [9, 8, 18, 19]
pdr = 0.05

[[client]]
id = 21
connected_drone_ids = [27, 20]

[[server]]
id = 30
connected_drone_ids = [24, 25]